codecov:
  require_ci_to_pass: yes
  token: 4360524b-524c-4312-8f45-6a7d7a324ede
coverage:
  status:
    patch: no
    project:
      default:
        threshold: 1%
        if_not_found: success
    changes: no
  precision: 2
  range: "50...100"
ignore:
 - "rpc/src/main/java/com/distkv/rpc/protobuf/generated"
 - "client/src/main/java/com/distkv/client/example"
 - "client/src/main/java/com/distkv/asyncclient/example"
 - "test/.*"
 - ".github/.*"
 - "*.xml"
 - ".style/.*"
 - "*.md"
 - "*.sh"
 - "scripts/.*"
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
