version: "2"
services:
  distkv:
    container_name: distkv
    image: dst0519/distkv:0.1.4
    mem_limit: 1073741824 # 1G
    ports:
      - "8082:8082"
    volumes:
      - ./logs/:/tmp/distkv/logs/
    environment:
      {
        JAVA_OPTS: -Xms820m -Xmx820m
      }
