/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_distkv_storageengine_StorageEngineNativeImpl */

#ifndef _Included_com_distkv_storageengine_StorageEngineNativeImpl
#define _Included_com_distkv_storageengine_StorageEngineNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_distkv_storageengine_StorageEngineNativeImpl
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_distkv_storageengine_StorageEngineNativeImpl_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_distkv_storageengine_StorageEngineNativeImpl
 * Method:    nativeDestory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_distkv_storageengine_StorageEngineNativeImpl_nativeDestory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_distkv_storageengine_StorageEngineNativeImpl
 * Method:    nativePut
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_distkv_storageengine_StorageEngineNativeImpl_nativePut
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_distkv_storageengine_StorageEngineNativeImpl
 * Method:    nativeGet
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_distkv_storageengine_StorageEngineNativeImpl_nativeGet
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif